mongo:
  host: 68.169.54.122
  port: 27017
  db: quantocusta-dsv


# Logging settings.
logging:
  level: INFO
  
  # Logger-specific levels.
  loggers:
    "sb.quantocusta": DEBUG
    "com.yammer.dropwizard.auth": DEBUG


# HTTP-specific options.
http:

  port: 8090
  adminPort: 8090
  
  # Configuration parameters for GZIP encoding of response entities.
  gzip:
    enabled: true