mongo:
  host: localhost
  port: 27017
  db: quantocusta


# Logging settings.
logging:
  level: INFO
  
  # Logger-specific levels.
  loggers:
    "sb.quantocusta": INFO


# HTTP-specific options.
http:

  port: 8090
  adminPort: 8090
  adminUsername: quantocusta
  adminPassword: fanipituchasimba
  
  # The number of threads dedicated to accepting connections.
  acceptorThreads: 2
  
  acceptQueueSize: 1024

  # Configuration parameters for GZIP encoding of response entities.
  gzip:
    enabled: false