mongo:
  host: <host>
  port: <port>
  db: <db>
  user: <user>
  pwd: <pwd>


# Logging settings.
logging:
  level: INFO
  
  # Logger-specific levels.
  loggers:
    "sb.quantocusta": INFO


# HTTP-specific options.
http:

  port: <port>
  adminPort: <port>
  # adminUsername: ***********
  # adminPassword: ***************
  
  # The number of threads dedicated to accepting connections.
  acceptorThreads: 2
  
  acceptQueueSize: 1024

  # Configuration parameters for GZIP encoding of response entities.
  gzip:
    enabled: false
